name: Build and push to ECR

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Dockerfile name'
        required: false
        type: string
        default: Dockerfile
      ecr_repository_name:
        description: 'ECR repository name'
        required: true
        type: string
      image_tag:
        description: 'Custom image tag (optional, defaults to github.sha)'
        required: false
        type: string
      runs_on:
        description: 'Custom Actions runner (optional, defaults to ubuntu-latest)'
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      AWS_REGION:
        required: true
      AWS_ROLE_TO_ASSUME:
        required: true
      AWS_ECR_REGISTRY:
        required: true
    outputs:
      image_tag:
        description: "The tag of the built image"
        value: ${{ jobs.build.outputs.image_tag }}

permissions:
  contents: read
  id-token: write

env: {}

jobs:
  build:
    name: Build and push Docker image
    runs-on: ${{ inputs.runs_on }}
    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}
      image_uri: ${{ steps.meta.outputs.image_uri }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image metadata
        id: meta
        run: |
          IMAGE_TAG="${{ inputs.image_tag || github.sha }}"
          IMAGE_URI="${{ secrets.AWS_ECR_REGISTRY }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${IMAGE_TAG}"

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_uri=${IMAGE_URI}" >> $GITHUB_OUTPUT

          echo "🏗️ Building image with tag: ${IMAGE_TAG}"
          echo "📦 Full image URI: ${IMAGE_URI}"

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ inputs.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.meta.outputs.image_uri }}
            ${{ secrets.AWS_ECR_REGISTRY }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.ecr_repository_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build summary
        run: |
          echo "✅ Build completed successfully!"
          echo "📦 Image: ${{ steps.meta.outputs.image_uri }}"
          echo "🏷️ Tag: ${{ steps.meta.outputs.image_tag }}"
