name: DEV | Build to ECR and deploy to EKS

on:
  push:
    branches: [develop]
  workflow_dispatch:

env: {}

permissions:
  contents: read
  id-token: write

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: build-push-api-dev
        uses: ./.github/actions/build-push.yml@master
        with:
          ecr_repository_name: ${{ vars.AWS_ECR_REPOSITORY_NAME || 'hook0-api' }}
          runs_on: ubuntu-latest
          dockerfile: api/Dockerfile

      - name: update-manifest-api-dev
        uses: ./.github/actions/update-manifest.yml@master
        with:
          manifest_path: apps/dev/values/hook0-api.yaml
          runs_on: ubuntu-latest

  # build-push-frontend-dev:
  #   uses: .github/actions/build-push.yml
  #   with:
  #     ecr_repository_name: ${{ vars.AWS_ECR_REPOSITORY_NAME || 'hook0-frontend' }}
  #     runs_on: arc-runner-set
  #     dockerfile: frontend/Dockerfile
  #   secrets:
  #     AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  # update-manifest-frontend-dev:
  #   uses: .github/actions/update-manifest.yml
  #   needs: build-push-frontend-dev
  #   with:
  #     manifest_path: apps/dev/values/hook0-frontend.yaml
  #     runs_on: arc-runner-set
  #   secrets:
  #     AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # build-push-output-worker-dev:
  #   uses: .github/actions/build-push.yml
  #   with:
  #     ecr_repository_name: ${{ vars.AWS_ECR_REPOSITORY_NAME || 'hook0-output-worker' }}
  #     runs_on: arc-runner-set
  #     dockerfile: output-worker/Dockerfile
  #   secrets:
  #     AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  # update-manifest-output-worker-dev:
  #   uses: .github/actions/update-manifest.yml
  #   needs: build-push-output-worker-dev
  #   with:
  #     manifest_path: apps/dev/values/hook0-output-worker.yaml
  #     runs_on: arc-runner-set
  #   secrets:
  #     AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
