name: DEV | Build to ECR and deploy to EKS

on:
  push:
    branches: [develop]
  workflow_dispatch:

env: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-push-api-dev:
    uses: bancoboreal/shared-actions/.github/workflows/build-push.yml@main
    with:
      ecr_repository_name: ${{ vars.AWS_ECR_REPOSITORY_NAME || 'hook0-api' }}
      runs_on: arc-runner-set
      dockerfile: api/Dockerfile
    secrets:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  update-manifest-api-dev:
    uses: bancoboreal/shared-actions/.github/workflows/update-manifest.yml@main
    needs: build-push-api-dev
    with:
      manifest_path: apps/dev/values/hook0-api.yaml
      runs_on: arc-runner-set
    secrets:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-push-frontend-dev:
    uses: bancoboreal/shared-actions/.github/workflows/build-push.yml@main
    with:
      ecr_repository_name: ${{ vars.AWS_ECR_REPOSITORY_NAME || 'hook0-frontend' }}
      runs_on: arc-runner-set
      dockerfile: frontend/Dockerfile
    secrets:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  update-manifest-frontend-dev:
    uses: bancoboreal/shared-actions/.github/workflows/update-manifest.yml@main
    needs: build-push-frontend-dev
    with:
      manifest_path: apps/dev/values/hook0-frontend.yaml
      runs_on: arc-runner-set
    secrets:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-push-output-worker-dev:
    uses: bancoboreal/shared-actions/.github/workflows/build-push.yml@main
    with:
      ecr_repository_name: ${{ vars.AWS_ECR_REPOSITORY_NAME || 'hook0-output-worker' }}
      runs_on: arc-runner-set
      dockerfile: output-worker/Dockerfile
    secrets:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  update-manifest-output-worker-dev:
    uses: bancoboreal/shared-actions/.github/workflows/update-manifest.yml@main
    needs: build-push-output-worker-dev
    with:
      manifest_path: apps/dev/values/hook0-output-worker.yaml
      runs_on: arc-runner-set
    secrets:
      AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
